name = str(input("\nRegistrese ingresando su nombre: "))
edad = int(input("\nIngrese sus edad: "))
print(f"\nBienvenido {name}, gracias por registrarse")
print("Ya puede hacer uso de nuestros servicios")
exit()
